2025-06-11 09:15:21,351 ERROR: Exception on /magic-login/InBhdml0aHJhZ29waXN0dHlAZ21haWwuY29tIg.aElJHQ.LPhfMeMUmM1GqELw46DF_5O9CdU [GET] [in /home/ec2-user/GNCleanVideo1/venv/lib64/python3.9/site-packages/flask/app.py:875]
Traceback (most recent call last):
  File "/home/ec2-user/GNCleanVideo1/venv/lib64/python3.9/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ec2-user/GNCleanVideo1/venv/lib64/python3.9/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ec2-user/GNCleanVideo1/venv/lib64/python3.9/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ec2-user/GNCleanVideo1/venv/lib64/python3.9/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/ec2-user/GNCleanVideo1/app.py", line 230, in magic_login
    session.permanent = True  # Make the session persistent
  File "/home/ec2-user/GNCleanVideo1/venv/lib64/python3.9/site-packages/flask/templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "/home/ec2-user/GNCleanVideo1/venv/lib64/python3.9/site-packages/jinja2/environment.py", line 1087, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/ec2-user/GNCleanVideo1/venv/lib64/python3.9/site-packages/jinja2/environment.py", line 1016, in get_template
    return self._load_template(name, globals)
  File "/home/ec2-user/GNCleanVideo1/venv/lib64/python3.9/site-packages/jinja2/environment.py", line 975, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/ec2-user/GNCleanVideo1/venv/lib64/python3.9/site-packages/jinja2/loaders.py", line 138, in load
    code = environment.compile(source, name, filename)
  File "/home/ec2-user/GNCleanVideo1/venv/lib64/python3.9/site-packages/jinja2/environment.py", line 771, in compile
    self.handle_exception(source=source_hint)
  File "/home/ec2-user/GNCleanVideo1/venv/lib64/python3.9/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/ec2-user/GNCleanVideo1/templates/upload_stats.html", line 83, in template
    {% set pts = video.points | fromjson %}
jinja2.exceptions.TemplateAssertionError: No filter named 'fromjson'.
